name: NASA  Project CI
on:
  push:
    branchas: [ master ]
  pull_request:
    branches: [ master ]
  jobs:
    build:
      env:
        CI: true
        MONGO_URL: 'mongodb://localhost:27017/nasa-api'
      strategy:
        matrix:
          node-version: [20.x]
          mongodb-version: ['4.4']
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js version ${{ matrix.node-version}}
        - uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version}}
        - name: Use MongoDB in GitHub Actions
          uses: supercharge/mongodb-github-action@1.6.0
          with:
            mongodb-version: ${{ matrix.mongodb-version}}
        - run: npm install
        - run: npm run build --prefix client
        - run: npm test
      # deploy:
        # needs: build
